const AchNames ={
  a1: "Time to charge my battery!",
  a2: "Your battery is full!",
  a3: "Your battery is kilofull!",
  a4: "Your battery is megafull!",
  a5: "Your battery is gigafulll!",
  a6: "Your battery is terafull",
  a7: "Your battery is petafull",
  a8: "Your battery is exafull!",
  a9: "Your battery is zettafull!",
  a10: "Your battery is yottafull",
  a11: "Your battery is rontafull",
  a12: "Your battery is quettafull",
  a13: "Your battery is [SOFTCAPPED]",
  a14: "Chargize",
  a15: "Dual Chargize",
  a16: "Triple Chargize",
  a17: "2 challenges",
  a18: "Vigintibattery",
  a19: "Fast Chargerize",
  a20: "VERY fast Chargerize",
  a21: "Power lines",
  a22: "Power challenge 1",
  a23: "Your battery has exploded",
  a24: "How did I get here?",
}
